

NEEDS .S    FROM DSK1.TOOLS
NEEDS VALUE FROM DSK1.VALUES
NEEDS DEFER FROM DSK1.DEFER
NEEDS BLOCK FROM DSK1.BLOCKS

: NODE ( L R DATA -- NODE ) HERE >R , , , R> ;
: LEAF ( DATA -- NODE ) 0 0 ROT NODE ;

: >DATA  ( NODE -- data) POSTPONE @ ; IMMEDIATE

: >RIGHT ( NODE -- data) CELL+ >DATA ;
: >LEFT  ( NODE -- data) CELL+ CELL+ >DATA ;
