CREATE FUEL
       BYTES 6 BF DF FF 80 38 93 6
       BYTES 2 80 36 6
       BYTES 2 80 34 6
       BYTES 2 80 32 6
       BYTES 3 80 30 95 6
       BYTES 2 80 2E 6
       BYTES 2 80 2C 6
       BYTES 2 80 2A 6
       BYTES 2 80 28 6
       BYTES 2 80 27 6
       BYTES 2 80 26 6
       BYTES 2 80 25 6
       BYTES 2 80 24 6
       BYTES 2 80 23 5
       BYTES 2 80 22 5
       BYTES 3 80 21 97 4
       BYTES 2 80 20 4
       BYTES 2 80 1F 4
       BYTES 2 80 1E 3
       BYTES 2 80 1D 3
       BYTES 2 80 1C 3
       BYTES 2 80 1B 3
       BYTES 2 80 1A 3
       BYTES 2 80 19 3
       BYTES 2 80 18 3
       BYTES 2 80 17 3
       BYTES 2 80 16 3
       BYTES 2 80 15 3
       BYTES 2 80 14 3
       BYTES 2 80 13 3
       BYTES 2 80 12 3
       BYTES 2 80 11 3
       BYTES 2 80 10 3
/END
