\ named colors for Graphics programs
CR .( Aug 9 2023 to uses some TI-Logo names)

: ENUM  ( 0 <text> -- n) DUP CONSTANT  1+ ;

1 ( set 1st color)
ENUM CLR      \ 1
ENUM BLACK    \ 2
ENUM GREEN    \ 3
ENUM LIME     \ 4
ENUM BLUE     \ 5
ENUM SKY      \ 6
ENUM RED      \ 7
ENUM CYAN     \ 8
ENUM RUST     \ 9
ENUM ORANGE   \ 10
ENUM YELLOW   \ 11
ENUM LEMON    \ 12
ENUM OLIVE    \ 13
ENUM PURPLE  \ 14
ENUM GRAY     \ 15
ENUM WHITE    \ 16
DROP
